import { Flex } from '@chakra-ui/react'
import Head from 'next/head'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex width="400px" margin="auto" bg="red">
        <h1>Hello Word!</h1>
      </Flex>
     
    </div>
  )
}

